version: '3.9'
services:
  next-app:
    build: .
    container_name: mfaouzi.com

  nginx:
    build: ./nginx/docker
    container_name: nginx
    depends_on:
      - next-app
    ports:
      - '80:80'
      - '8080:80'
